### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by akhon**
- ossec-agent restarts after registers on ossec-server
- updated ossec.conf template by ossec-wazuh default config

### CODE REVIEW

**Comment by mahmoudimus** [comment]
this looks fine for me. @akhon can you confirm that `restart-ossec.sh` is available here. i'm not sure where that is.

**Comment by akhon** [comment]
@mahmoudimus: `notify ossec restart` will push `service ossec restart`, confirm that ossec has been registered as a service during installation

**Comment by mahmoudimus** [comment]
@akhon just want to make sure that `restart-ossec.sh` is an actual file taht exists on teh agents.

**Comment by akhon** [comment]
@mahmoudimus: yes, it exists in `/var/ossec/active-response/bin/restart-ossec.sh`

**Comment by mahmoudimus** [comment]
:+1: :shipit:

**Pull request merged**
